### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Anastaiisha** [Daniil193/Simple_KG#2]
Даниил, спасибо огромное за датасет!
К сожалению, я не знаю как на гитхабе можно напрямую вам написать, поэтому попробую так)
Можно еще уточнить, что значит столбец "theme_value"? Это разделение на темы качество окр. среды, городской и доля дорожной среды, соответствующей нормативам?

**Comment by Daniil193** [comment]
Верно, в примере theme_value используется лишь для рассмотрения в разрезе отдельной проблемы, поэтому в ноутбуке, начиная с этапа Tokenizing, рассматривается только одна тема:
full_corpus = df_0["message"].values
Затем можно повторить для оставшихся.

**Comment by Anastaiisha** [comment]
Спасибо!
Пожалуйста, если можете поотвечать на вопросы по вашему коду, не закрывайте эту тему
Я пока потихоньку разбираюсь в базах знаний и их построении, поэтому скорее всего они возникнут)

**Comment by Anastaiisha** [comment]
Даниил, а откуда модуль script_for_graph для визуализации графа? Среди пакетов такого похоже нет

**Comment by Anastaiisha** [comment]
> Верно, в примере theme_value используется лишь для рассмотрения в разрезе отдельной проблемы, поэтому в ноутбуке, начиная с этапа Tokenizing, рассматривается только одна тема: full_corpus = df_0["message"].values Затем можно повторить для оставшихся.

**Comment by Daniil193** [comment]
Данный модуль формировал по примерам с некоторыми корректировками: https://visjs.github.io/vis-network/examples/
Чтобы осуществлять отрисовку в оффлайн режиме необходимо либо вставить в модуль script_for_graph скрипты:
- https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.css
- https://visjs.github.io/vis-network/standalone/umd/vis-network.min.js
Либо скачать их и указать корректные пути в script_for_graph :
       
- link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.css"                
- script src="https://visjs.github.io/vis-network/standalone/umd/vis-network.min.js"></sc

**Comment by Anastaiisha** [comment]
Спасибище!)
А то уже начала писать альтернативный код, а он бы точно был более кривым

**Comment by Daniil193** [comment]
Как альтернатива, но со своими ограничениями, можно отрисовать в jupyter dash.
Простой пример:

[j_dash_example.txt](https://github.com/Daniil193/Simple_KG/files/8639529/j_dash_example.txt)

**Comment by Daniil193** [comment]
.
